### ISSUE TITLE
[Suggestion] color값 변경 요청

### ISSUE THREAD

**Issue by ByeongminLee** [Team-Stuckyi/TheGreatCatsby-FrontEnd#13]
# [Suggestion] color값 변경 요청

## 제안 사항
무분별한 컬러 사용 방지를 위해 다음과 같이 모든 컬러값 지정시 변수로 사용 할 것

## 작업 내용
- 다음 커밋 https://github.com/Team-Stuckyi/TheGreatCatsby-FrontEnd/commit/ecbf6793be7e67d9e5e370d8763f875355b78adf 참조
- 컬러값 변수로 지정

### 1. 일반 css에서 사용
  - 기존 컬러값 입력
    ```jsx
    border: 2px solid #808080;
    ```
  - 변경된 컬러값 입력
    ```jsx
    border: 2px solid var(--gray500);
    ```

### 2. 기존에 컬러를 문자열로 사용할 경우
  > 참고 파일 <code>Button.js</code> 컴포넌트 21번줄
  - 기존 컬러값 입력
    ```jsx
    color: ${props => props.fontColor || '#f76b8a'};
    ```
  - 변경된 컬러값 입력
    ```jsx
    color: ${props => props.fontColor || 'var(--white)'};
    ```

**Comment by 0x000613** [comment]
오늘중으로 해놓겠습니다.
