### ISSUE TITLE
[Suggestion] Input.js 수정 요청

### ISSUE THREAD

**Issue by 0x000613** [Team-Stuckyi/TheGreatCatsby-FrontEnd#42]
`Button.js` 컴포넌트에 `margin`, `focus`, `padding`  옵션에 값 넣을수 있도록 수정 부탁드립니다.

`focus`
- Input 태그 클릭시 outline 색상을 설정할 수 있도록 수정 (Input 요소를 클릭했을때 테두리에 색상을 표시할 수 있도록)

`margin`
- 상, 하, 좌, 우에 `margin` 옵션을 줄 수 있도록 수정

`padding`
- 상, 하, 좌, 우에 `padding` 옵션을 줄 수 있도록 수정

**Comment by cksals3753** [comment]
수정해서 Thankyou 브랜치에 올려놓았습니다.
