### ISSUE TITLE
[Suggestion] Search.js 수정 요청

### ISSUE THREAD

**Issue by heejj1206** [Team-Stuckyi/TheGreatCatsby-FrontEnd#48]
# [Suggestion] Search.js 수정 요청

## 목적
목업 페이지의 디자인과 맞추기 위함

## 요청 내용
button과 input 의 높이 차이 수정
select, input, button  사이 margin 수정
select 에 radius 추가
input border-color 수정
categoryCount 기능

## 참고 이미지

목업 페이지
![스크린샷 2022-03-01 오전 12 08 18](https://user-images.githubusercontent.com/85618700/156007206-bbca37fb-1489-4f0d-b995-a592dbe32aee.png)

현재 Search.js
![스크린샷 2022-03-01 오전 12 08 27](https://user-images.githubusercontent.com/85618700/156007238-0cbf6433-3fc5-4320-9406-b512bad264d3.png)

**Comment by 0x000613** [comment]
#62 수정 확인 부탁드립니다.
