### ISSUE TITLE
[Suggestion] TableList.js 수정 요청

### ISSUE THREAD

**Issue by abcabcp** [Team-Stuckyi/TheGreatCatsby-FrontEnd#57]
- 요청 내용
관리 밑에 수정, 삭제 버튼이 올 수 있도록 변경 요청
button 안의 글자 수정 가능하게 요청 (삭제-> 탈퇴로 바꿀 수 있게..)

- 참고 이미지
![테이블](https://user-images.githubusercontent.com/84028062/156343783-a8342061-a45b-4620-ae08-bde064d7128e.png)

**Comment by ByeongminLee** [comment]
1. 아래 사진과 같이 고치면 됩니다.

![스크린샷 2022-03-02 오후 7 30 12](https://user-images.githubusercontent.com/71276006/156344652-907235ca-467c-4f56-a146-a9ccc35d17ed.png)


2. 아래 사진과 같이 삭제 또는 수정만 있는 경우가 있습니다.3. 

![스크린샷 2022-03-02 오후 7 30 31](https://user-images.githubusercontent.com/71276006/156344731-73997f69-3d00-47c0-b2a5-935da212c17b.png)

**Comment by abcabcp** [comment]
+ 상위 컴포넌트에서도 사용할 수 있도록 버튼에 onClick 이벤트를 걸어둬야함

**Comment by abcabcp** [comment]
+ <Input value={cur[key]} /> 여기에도...  onChange ..
