### ISSUE TITLE
[Suggestion] 수정 사항

### ISSUE THREAD

**Issue by ByeongminLee** [Team-Stuckyi/TheGreatCatsby-FrontEnd#80]
# [Suggestion] 수정 사항

## 김우영
- [x] 이슈 확인 체크

- [x] User페이지의 Header 오른쪽 마진 
   ![1](https://user-images.githubusercontent.com/71276006/160536601-4b7c7fbe-763d-468f-8781-cfacd190885a.png)

- [x] Gobal 스타일 확인
   admin 로그인에서만 적용되어야하는 Background 컬러가 전체 페이지에 적용됨

- [x] 리뷰 버튼 수정
   리뷰 버튼이 잘 보이지 않기 때문에 구매 후기 + 버튼을 다음과 같이 [리뷰 더보기 +]로 해서 오른쪽 영역으로 수정 할 것
   ![2](https://user-images.githubusercontent.com/71276006/160536732-4063cc17-37b3-4aff-ac55-493b5b9d6839.png)

- [x] 상품 리뷰 페이지 이동 주소 수정
  현재 :  <code>/products/{number}/review</code>
  변경사항 :  <code>/reviews/{number}</code>

- [x]  로딩 컴포넌트 적용
  페이지별로 데이터를 불러오는 공간에 로딩 컴포넌트 적용
  댓글로 변경된 파일과 페이지 적을 것

- [x] 상품 정보 더보기를 클릭하여 열려 있을 경우 닫기로 변경
   ![3](https://user-images.githubusercontent.com/71276006/160537024-874ad6fd-fe97-4cd0-9af5-7c8d2aab7f52.png)

- [x] 컴포넌트 폴더 정리
   컴포넌트가 잘못된 폴더에 들어가 있음
   1. 잘못된 폴더를 고치고 해당 파일을 사용하고 있는 모든 파일 수정 할 것
   2. 변경 사항을 댓글로 작성 할 것
   Ex) Search.js의 경우 admin에서만 사용하지만 현재 common에 들어가 있다. 
   ⭐ 경로가 변경된 컴포넌트와 컴포넌트를 가지고 있는 파일의 경로도 같이 수정하여 '해당 파일별로' 하나의 커밋을 하고
   ⭐ 변경 사항을 댓글로 작성할 시에는 해당 커밋과 해당 파일의 경로를 명시할 것

<br/>

## 노희재
- [x] 이슈 확인 체크

- [x] 로딩 컴포넌트 적용
  페이지 별로 데이터를 불러오는 공간에 로딩 컴포넌트 적용
  → 관리자 페이지의 경우 임의로 적용하려고 했으나 ManageOrder,ManageProd에는 따로 slice에 Loading을 받지 않아서 적용 못함 
  댓글로 변경된 파일과 페이지 적을 것

- [x] 로그인 페이지 접속 오류
   사용자 페이지에서 로그인 페이지(   <code>members/login</code> ) 접속이 안됨

- [x] 컴포넌트 폴더 정리
   컴포넌트가 잘못된 폴더에 들어가 있음
   1. 잘못된 폴더를 고치고 해당 파일을 사용하고 있는 모든 파일 수정 할 것
   2. 변경 사항을 댓글로 작성 할 것
   Ex) TableList.js의 경우 admin에서만 사용하지만 현재 common에 들어가 있다.
   ⭐ 경로가 변경된 컴포넌트와 컴포넌트를 가지고 있는 파일의 경로도 같이 수정하여 '해당 파일별로' 하나의 커밋을 하고
   ⭐ 변경 사항을 댓글로 작성할 시에는 해당 커밋과 해당 파일의 경로를 명시할 것

<br/>

## 전찬민
- [x] 이슈 확인 체크

- [x] 라우터 확인
   <code>showmethemoney</code>, <code>thankyou</code> 페이지의 경우 라우터가 여러개임

- [x]  로딩 컴포넌트 적용
   페이지 별로 데이터를 불러오는 공간에 로딩 컴포넌트 적용
   댓글로 변경된 파일과 페이지 적을 것

**Comment by 0x000613** [comment]
1. 전체 페이지 레이아웃에 영향을 미치는 AdminLogin.css를 제거
2. 리뷰 작성 버튼을 조금 더 가시성이 좋아보이도록 우측 배치하고 글씨 삽입
3. 리뷰 작성 버튼 클릭시 정상적인 상품 리뷰 페이지로 이동할 수 있도록 링크 수정
4. 작업한 모든 페이지에 로딩 컴포넌트가 적용되도록 수정
5. 상품정보 더보기 클릭시 닫기로 전환되는 기능 추가
6. Search.js 경로를 Admin Components 디렉토리로 변경함, 또한 Search.js를 참조하는 모든 파일에서 경로를 변경된 경로로 수정
7. ProdList 페이지에서 리뷰 평점, 리뷰 개수가 정적으로 표기되던것을 동적으로 표기하도록 변경함

**Comment by heejj1206** [comment]
1. '주문 관리 페이지, 상품 관리 페이지, 사용자 로그인 페이지, 회원 가입 페이지' 에 로딩 창 기능을 추가하기 위하여 해당 페이지들에 사용되는 파일인 ManageOrder, ManageProd, Login, Register, ManageOrderSlice, ManageProdSlice, JoinSlice, LoginSlice 파일들 수정
2. 로그인 페이지 접속 오류 해결 완료
3. TableList, TableListWithoutPagination 파일 위치와 해당 컴포넌트를 사용 중인 파일들에서 경로 수정 완료
